apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zh0euiv62-python 
  janus-idp.io/tekton: zh0euiv62-python
  backstage.io/kubernetes-id: zh0euiv62-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zh0euiv62-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml