apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zh0euiv62-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zh0euiv62-python 
  name: zh0euiv62-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zh0euiv62-python 
